import React, { useState, useEffect } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faUpload, faTrash, faFileCode, faCheckCircle, faLightbulb } from '@fortawesome/free-solid-svg-icons';
import { useAuth } from '../context/AuthContext';
import './ApiSchemaUpload.css';

const ApiSchemaUpload = ({ projectId, onTestsGenerated }) => {
  const [schemas, setSchemas] = useState([]);
  const [uploading, setUploading] = useState(false);
  const [selectedFile, setSelectedFile] = useState(null);
  const [schemaName, setSchemaName] = useState('');
  const [schemaDescription, setSchemaDescription] = useState('');
  // Library of API calls built from a schema: shown for one schema at a time
  const [openSchemaId, setOpenSchemaId] = useState(null);
  const [operations, setOperations] = useState([]);
  const [loadingOperations, setLoadingOperations] = useState(false);
  const [operationFilter, setOperationFilter] = useState('');
  // Baseline API tests: built on the server from the library of calls, no AI involved
  const [generatingSchemaId, setGeneratingSchemaId] = useState(null);
  const [generationResult, setGenerationResult] = useState(null);
  // Scenario ideas: suggested by AI for one schema; the chosen ones become API tests generated by AI
  const [suggestingSchemaId, setSuggestingSchemaId] = useState(null);
  const [ideas, setIdeas] = useState(null); // { schemaId, schemaName, items: [{...idea, checked}] }
  const [environments, setEnvironments] = useState([]);
  const [ideasEnvironmentId, setIdeasEnvironmentId] = useState('');
  const [creatingScenarios, setCreatingScenarios] = useState(false);
  const [suggestingMore, setSuggestingMore] = useState(false);
  // Scenario tests created without steps (their generation did not finish), per schema id
  const [pendingTests, setPendingTests] = useState({});
  const [queuingSchemaId, setQueuingSchemaId] = useState(null);
  const [scenarioResult, setScenarioResult] = useState(null);
  const { getAuthHeaders } = useAuth();
  const API_URL = process.env.REACT_APP_API_URL;

  useEffect(() => {
    if (projectId && projectId !== 'all') {
      fetchSchemas();
    }
  }, [projectId]);

  const fetchSchemas = async () => {
    try {
      const response = await fetch(`${API_URL}/api/projects/${projectId}/api-schemas`, {
        headers: getAuthHeaders()
      });
      
      if (response.ok) {
        const data = await response.json();
        setSchemas(data.schemas || []);
        fetchPendingTests(data.schemas || []);
      }
    } catch (error) {
      console.error('Error fetching schemas:', error);
    }
  };

  const fetchPendingTests = async (list) => {
    const found = {};
    await Promise.all(list.map(async (schema) => {
      try {
        const response = await fetch(`${API_URL}/api/api-schemas/${schema.id}/scenario-tests/pending`, { headers: getAuthHeaders() });
        if (response.ok) found[schema.id] = (await response.json()).tests || [];
      } catch (error) { /* the button is just not shown */ }
    }));
    setPendingTests(found);
  };

  // Generate the steps of the scenario tests that have none: e.g. after the model's quota ran out
  const handleGeneratePending = async (schema) => {
    const tests = pendingTests[schema.id] || [];
    setQueuingSchemaId(schema.id);
    try {
      const envResponse = await fetch(`${API_URL}/api/projects/${projectId}/environments`, { headers: getAuthHeaders() });
      const envData = envResponse.ok ? await envResponse.json() : [];
      const list = Array.isArray(envData) ? envData : (envData.environments || []);
      const environment = list.find(env => env.api_url) || list[0];
      if (!environment) throw new Error('this project has no environment; add one with the API URL of this API');
      if (!window.confirm(`Generate the steps of ${tests.length} scenario test${tests.length === 1 ? '' : 's'} on the environment "${environment.name}"? AI generates them one test after another.`)) return;
      const response = await fetch(`${API_URL}/api/api-schemas/${schema.id}/scenario-tests/generate`, {
        method: 'POST',
        headers: getAuthHeaders(),
        body: JSON.stringify({ environment_id: environment.id })
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.detail || `HTTP ${response.status}`);
      setIdeas(null);
      setGenerationResult(null);
      setScenarioResult({ schemaName: schema.name, created: data.queued, skipped: [], requeued: true });
      setPendingTests(prev => ({ ...prev, [schema.id]: [] }));
      if (onTestsGenerated) onTestsGenerated();
    } catch (error) {
      console.error('Error queuing scenario tests:', error);
      alert(`Failed to start the generation: ${error.message}`);
    } finally {
      setQueuingSchemaId(null);
    }
  };

  const toggleOperations = async (schemaId) => {
    if (openSchemaId === schemaId) {
      setOpenSchemaId(null);
      return;
    }
    setOpenSchemaId(schemaId);
    setOperations([]);
    setOperationFilter('');
    setLoadingOperations(true);
    try {
      const response = await fetch(`${API_URL}/api/projects/${projectId}/api-operations?schema_id=${schemaId}`, {
        headers: getAuthHeaders()
      });
      if (response.ok) {
        const data = await response.json();
        setOperations(data.operations || []);
      }
    } catch (error) {
      console.error('Error fetching API calls:', error);
    } finally {
      setLoadingOperations(false);
    }
  };

  const handleGenerateTests = async (schema) => {
    setGeneratingSchemaId(schema.id);
    setGenerationResult(null);
    try {
      const response = await fetch(`${API_URL}/api/api-schemas/${schema.id}/baseline-tests`, {
        method: 'POST',
        headers: getAuthHeaders()
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.detail || `HTTP ${response.status}`);
      setGenerationResult({ schemaId: schema.id, schemaName: schema.name, created: data.created, skipped: data.skipped });
      fetchSchemas();
      if (onTestsGenerated) onTestsGenerated();
    } catch (error) {
      console.error('Error generating API tests:', error);
      alert(`Failed to generate API tests: ${error.message}`);
    } finally {
      setGeneratingSchemaId(null);
    }
  };

  const fetchEnvironments = async () => {
    try {
      const response = await fetch(`${API_URL}/api/projects/${projectId}/environments`, { headers: getAuthHeaders() });
      if (!response.ok) return;
      const data = await response.json();
      const list = Array.isArray(data) ? data : (data.environments || []);
      setEnvironments(list);
      // The API is called on the API URL of the environment: prefer one that has it
      const preferred = list.find(env => env.api_url) || list[0];
      setIdeasEnvironmentId(preferred ? String(preferred.id) : '');
    } catch (error) {
      console.error('Error fetching environments:', error);
    }
  };

  const handleSuggestScenarios = async (schema) => {
    setSuggestingSchemaId(schema.id);
    setIdeas(null);
    setScenarioResult(null);
    setGenerationResult(null);
    fetchEnvironments();
    try {
      const response = await fetch(`${API_URL}/api/api-schemas/${schema.id}/scenario-ideas`, {
        method: 'POST',
        headers: getAuthHeaders(),
        body: JSON.stringify({ count: 10 })
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.detail || `HTTP ${response.status}`);
      setIdeas({ schemaId: schema.id, schemaName: schema.name, items: data.scenarios.map(idea => ({ ...idea, checked: true })) });
    } catch (error) {
      console.error('Error suggesting scenarios:', error);
      alert(`Failed to suggest scenarios: ${error.message}`);
    } finally {
      setSuggestingSchemaId(null);
    }
  };

  // More ideas for the same schema: the model gets the ones already shown, so it does not repeat them
  const handleSuggestMore = async () => {
    setSuggestingMore(true);
    try {
      const response = await fetch(`${API_URL}/api/api-schemas/${ideas.schemaId}/scenario-ideas`, {
        method: 'POST',
        headers: getAuthHeaders(),
        body: JSON.stringify({ count: 10, exclude: ideas.items.map(({ name, description }) => ({ name, description })) })
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.detail || `HTTP ${response.status}`);
      setIdeas(prev => {
        const known = new Set(prev.items.map(idea => idea.name.toLowerCase()));
        const added = data.scenarios.filter(idea => !known.has(idea.name.toLowerCase())).map(idea => ({ ...idea, checked: true }));
        return { ...prev, items: [...prev.items, ...added] };
      });
    } catch (error) {
      console.error('Error suggesting more scenarios:', error);
      alert(`Failed to suggest more scenarios: ${error.message}`);
    } finally {
      setSuggestingMore(false);
    }
  };

  const toggleIdea = (index) => {
    setIdeas(prev => ({ ...prev, items: prev.items.map((idea, i) => i === index ? { ...idea, checked: !idea.checked } : idea) }));
  };

  const handleCreateScenarioTests = async () => {
    const chosen = ideas.items.filter(idea => idea.checked);
    setCreatingScenarios(true);
    try {
      const response = await fetch(`${API_URL}/api/api-schemas/${ideas.schemaId}/scenario-tests`, {
        method: 'POST',
        headers: getAuthHeaders(),
        body: JSON.stringify({
          scenarios: chosen.map(({ name, description }) => ({ name, description })),
          environment_id: ideasEnvironmentId ? Number(ideasEnvironmentId) : null
        })
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.detail || `HTTP ${response.status}`);
      setScenarioResult({ schemaName: ideas.schemaName, created: data.created, skipped: data.skipped });
      setIdeas(null);
      if (onTestsGenerated) onTestsGenerated();
    } catch (error) {
      console.error('Error creating scenario tests:', error);
      alert(`Failed to create the tests: ${error.message}`);
    } finally {
      setCreatingScenarios(false);
    }
  };

  const handleFileChange = (e) => {
    const file = e.target.files[0];
    setSelectedFile(file);
    
    // Auto-fill name from filename if empty
    if (file && !schemaName) {
      setSchemaName(file.name.replace(/\.[^/.]+$/, ""));
    }
  };

  const handleUpload = async () => {
    if (!selectedFile || !schemaName) {
      alert('Please select a file and provide a name');
      return;
    }

    setUploading(true);

    try {
      const formData = new FormData();
      formData.append('file', selectedFile);
      formData.append('name', schemaName);
      formData.append('description', schemaDescription);

      // No Content-Type here: the browser sets multipart/form-data with the boundary itself
      const response = await fetch(`${API_URL}/api/projects/${projectId}/api-schemas/upload`, {
        method: 'POST',
        headers: getAuthHeaders(false),
        body: formData
      });

      if (response.ok) {
        const data = await response.json();
        alert(`Schema "${schemaName}" ${data.updated ? 'updated' : 'uploaded'}: ${data.operations_count} API calls found.`);
        setOpenSchemaId(null);
        
        // Reset form
        setSelectedFile(null);
        setSchemaName('');
        setSchemaDescription('');
        document.getElementById('schema-file-input').value = '';
        
        // Refresh list
        fetchSchemas();
      } else {
        const error = await response.json();
        // A 422 from FastAPI carries a list of field errors, not a string
        const detail = Array.isArray(error.detail)
          ? error.detail.map((e) => `${(e.loc || []).join('.')}: ${e.msg}`).join('; ')
          : error.detail;
        alert(`Failed to upload schema: ${detail || 'Unknown error'}`);
      }
    } catch (error) {
      console.error('Error uploading schema:', error);
      alert('Failed to upload schema');
    } finally {
      setUploading(false);
    }
  };

  const handleDelete = async (schemaId) => {
    if (!window.confirm('Are you sure you want to delete this schema?')) {
      return;
    }

    try {
      const response = await fetch(`${API_URL}/api/api-schemas/${schemaId}`, {
        method: 'DELETE',
        headers: getAuthHeaders()
      });

      if (response.ok) {
        alert('Schema deleted successfully');
        if (openSchemaId === schemaId) setOpenSchemaId(null);
        fetchSchemas();
      } else {
        alert('Failed to delete schema');
      }
    } catch (error) {
      console.error('Error deleting schema:', error);
      alert('Failed to delete schema');
    }
  };

  if (!projectId || projectId === 'all') {
    return (
      <div className="api-schema-upload">
        <p className="no-project-message">Please select a specific project to manage API schemas</p>
      </div>
    );
  }

  return (
    <div className="api-schema-upload">
      <h3><FontAwesomeIcon icon={faFileCode} /> API Schema Management</h3>
      
      <div className="upload-section">
        <h4>Upload New Schema</h4>
        <div className="upload-form">
          <div className="form-group">
            <label>Schema File (JSON):</label>
            <input
              id="schema-file-input"
              type="file"
              accept=".json"
              onChange={handleFileChange}
              disabled={uploading}
            />
          </div>
          
          <div className="form-group">
            <label>Name:</label>
            <input
              type="text"
              value={schemaName}
              onChange={(e) => setSchemaName(e.target.value)}
              placeholder="e.g., Main API Schema"
              disabled={uploading}
            />
          </div>
          
          <div className="form-group">
            <label>Description (optional):</label>
            <textarea
              value={schemaDescription}
              onChange={(e) => setSchemaDescription(e.target.value)}
              placeholder="Description of this API schema"
              disabled={uploading}
            />
          </div>
          
          <button
            className="upload-button"
            onClick={handleUpload}
            disabled={uploading || !selectedFile || !schemaName}
          >
            <FontAwesomeIcon icon={faUpload} />
            {uploading ? ' Uploading...' : ' Upload Schema'}
          </button>
        </div>
      </div>

      <div className="schemas-list">
        <h4>Uploaded Schemas</h4>
        {schemas.length === 0 ? (
          <p className="no-schemas">No schemas uploaded yet. Upload a schema to enable accurate API test generation.</p>
        ) : (
          <div className="schemas-grid">
            {schemas.map(schema => (
              <div key={schema.id} className="schema-card">
                <div className="schema-header">
                  <FontAwesomeIcon icon={faCheckCircle} className="schema-icon" />
                  <h5>{schema.name}</h5>
                </div>
                <p className="schema-description">{schema.description || 'No description'}</p>
                <div className="schema-meta">
                  <span className="schema-type">{schema.schema_type}</span>
                  <span className="schema-date">
                    {new Date(schema.created_at).toLocaleDateString()}
                  </span>
                </div>
                <button
                  className="schema-calls-button"
                  onClick={() => toggleOperations(schema.id)}
                >
                  {openSchemaId === schema.id ? 'Hide API calls' : `Show API calls (${schema.operations_count ?? 0})`}
                </button>
                <button
                  className="schema-generate-button"
                  onClick={() => handleGenerateTests(schema)}
                  disabled={generatingSchemaId !== null || !schema.operations_count}
                  title="Read checks for every GET and create-read-update-delete chains per resource, built from the schema without AI"
                >
                  <FontAwesomeIcon icon={faFileCode} />
                  {generatingSchemaId === schema.id ? ' Generating...' : ' Generate API tests'}
                </button>
                <button
                  className="schema-ideas-button"
                  onClick={() => handleSuggestScenarios(schema)}
                  disabled={suggestingSchemaId !== null || creatingScenarios || !schema.operations_count}
                  title="AI suggests scenarios beyond the generated tests: flows across resources, negative checks, business rules. You pick which ones become tests."
                >
                  <FontAwesomeIcon icon={faLightbulb} />
                  {suggestingSchemaId === schema.id ? ' Thinking...' : ' Suggest scenarios (AI)'}
                </button>
                {(pendingTests[schema.id] || []).length > 0 && (
                  <button
                    className="schema-calls-button"
                    onClick={() => handleGeneratePending(schema)}
                    disabled={queuingSchemaId !== null}
                    title={`Scenario tests that were created but have no steps:\n${pendingTests[schema.id].map(test => test.name).join('\n')}`}
                  >
                    {queuingSchemaId === schema.id ? 'Starting...' : `Generate steps for ${pendingTests[schema.id].length} scenario test${pendingTests[schema.id].length === 1 ? '' : 's'}`}
                  </button>
                )}
                <button
                  className="delete-schema-button"
                  onClick={() => handleDelete(schema.id)}
                >
                  <FontAwesomeIcon icon={faTrash} /> Delete
                </button>
              </div>
            ))}
          </div>
        )}
      </div>

      {generationResult && (
        <div className="schema-generation-result">
          <h4>API tests of "{generationResult.schemaName}"</h4>
          <p>
            Created {generationResult.created.length} tests without AI
            {generationResult.skipped.length > 0 ? `, ${generationResult.skipped.length} already existed and were left as they are` : ''}.
            They are in Test Cases, under API Tests, in the group "{generationResult.schemaName}".
            Run them on an environment whose API URL points to this API; calls that need authorization log in with the environment's login and password.
          </p>
          {generationResult.created.length > 0 && (
            <ul>
              {generationResult.created.map(test => (
                <li key={test.id}>{test.name} ({test.steps} {test.steps === 1 ? 'step' : 'steps'})</li>
              ))}
            </ul>
          )}
        </div>
      )}

      {ideas && (
        <div className="schema-ideas">
          <h4>Scenario ideas for "{ideas.schemaName}" ({ideas.items.length})</h4>
          <p className="schema-ideas-hint">
            Suggested by AI. Pick the scenarios to keep: each becomes an API test in "{ideas.schemaName} / Scenarios",
            and AI generates its steps and runs them on the environment below, one test after another.
          </p>
          <ul className="schema-ideas-list">
            {ideas.items.map((idea, index) => (
              <li key={index} className={idea.checked ? 'checked' : ''}>
                <label>
                  <input type="checkbox" checked={idea.checked} onChange={() => toggleIdea(index)} />
                  <span className="schema-idea-name">{idea.name}</span>
                  {idea.kind && <span className={`schema-idea-kind kind-${idea.kind}`}>{idea.kind}</span>}
                </label>
                <div className="schema-idea-description">{idea.description}</div>
              </li>
            ))}
          </ul>
          <div className="schema-ideas-actions">
            {environments.length > 0 ? (
              <label>
                Environment:{' '}
                <select value={ideasEnvironmentId} onChange={(e) => setIdeasEnvironmentId(e.target.value)}>
                  {environments.map(env => (
                    <option key={env.id} value={env.id}>{env.name}{env.api_url ? ` (API: ${env.api_url})` : ''}</option>
                  ))}
                </select>
              </label>
            ) : (
              <span className="schema-ideas-warning">
                This project has no environment. Add one with the API URL of this API: the steps are run on it while they are generated.
              </span>
            )}
            <button
              className="schema-generate-button schema-ideas-create"
              onClick={handleCreateScenarioTests}
              disabled={creatingScenarios || suggestingMore || !ideasEnvironmentId || !ideas.items.some(idea => idea.checked)}
            >
              {creatingScenarios ? 'Creating...' : `Create ${ideas.items.filter(idea => idea.checked).length} tests`}
            </button>
            <button className="schema-calls-button schema-ideas-cancel" onClick={handleSuggestMore} disabled={creatingScenarios || suggestingMore}>
              {suggestingMore ? 'Thinking...' : 'Suggest more'}
            </button>
            <button className="schema-calls-button schema-ideas-cancel" onClick={() => setIdeas(null)} disabled={creatingScenarios || suggestingMore}>
              Cancel
            </button>
          </div>
        </div>
      )}

      {scenarioResult && (
        <div className="schema-generation-result">
          <h4>Scenario tests of "{scenarioResult.schemaName}"</h4>
          <p>
            {scenarioResult.requeued ? 'Generation started for' : 'Created'} {scenarioResult.created.length} tests
            {scenarioResult.skipped.length > 0 ? `, ${scenarioResult.skipped.length} already existed and were left as they are` : ''}.
            They are in Test Cases, under API Tests, in "{scenarioResult.schemaName} / Scenarios".
            AI is generating their steps one test after another; open a test to follow its progress.
          </p>
          {scenarioResult.created.length > 0 && (
            <ul>
              {scenarioResult.created.map(test => <li key={test.id}>{test.name}</li>)}
            </ul>
          )}
        </div>
      )}

      {openSchemaId && (
        <div className="schema-operations">
          <h4>API calls of "{(schemas.find(s => s.id === openSchemaId) || {}).name}"</h4>
          {loadingOperations ? (
            <p className="no-schemas">Loading...</p>
          ) : operations.length === 0 ? (
            <p className="no-schemas">No API calls found in this schema. Only OpenAPI and Swagger schemas in JSON are parsed.</p>
          ) : (
            <>
              <input
                type="text"
                className="operations-filter"
                value={operationFilter}
                onChange={(e) => setOperationFilter(e.target.value)}
                placeholder={`Filter ${operations.length} calls by path, name or resource`}
              />
              <div className="operations-table-container">
                <table className="operations-table">
                  <thead>
                    <tr>
                      <th>Method</th>
                      <th>Path</th>
                      <th>Name</th>
                      <th>Resource</th>
                      <th>Auth</th>
                      <th>Status</th>
                      <th>Response</th>
                    </tr>
                  </thead>
                  <tbody>
                    {operations
                      .filter(op => {
                        const needle = operationFilter.trim().toLowerCase();
                        return !needle || `${op.method} ${op.path} ${op.name} ${op.resource}`.toLowerCase().includes(needle);
                      })
                      .map(op => (
                        <tr key={op.id} title={op.summary || ''}>
                          <td><span className={`operation-method method-${op.method.toLowerCase()}`}>{op.method}</span></td>
                          <td className="operation-path">{op.path}</td>
                          <td>{op.name}</td>
                          <td>{op.resource}</td>
                          <td>{op.requires_auth ? 'yes' : '-'}</td>
                          <td>{op.expected_status}</td>
                          <td>{op.response.kind === 'none' ? '-' : op.response.kind}</td>
                        </tr>
                      ))}
                  </tbody>
                </table>
              </div>
            </>
          )}
        </div>
      )}
    </div>
  );
};

export default ApiSchemaUpload;
